<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup Label="Identity">
    <Product>Save Editor GUI Framework</Product>
    <Authors>nintendogamer15</Authors>
    <Copyright>Copyright (c) 2026 nintendogamer15</Copyright>
    <RepositoryUrl>https://github.com/nintendogamer15/save-editor-gui-framework</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix>alpha.1</VersionSuffix>
  </PropertyGroup>

</Project>
