<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SaveEditor.Ui/SaveEditor.Ui.csproj" />
    <ProjectReference Include="../../eng/SaveEditor.ScreenshotDiff/SaveEditor.ScreenshotDiff.csproj" />
  </ItemGroup>

</Project>
