<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>SaveEditor.PaletteGen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../palette/palette.json" LogicalName="palette.json" />
  </ItemGroup>

</Project>
